--- # continuous delivery pipeline settings used by the jenkins-jobdsl jobs
pipeline:
  type: java
  title: sapbw-enrich-booking
  group: microservice
jdk: jdk-8u40
chef:
  role: sapbw-enrich-booking
  app_name: sapbw-enrich-booking
maven:
  options: -DMSB_BROKER_HOST="rabbitmq-int.thomascook.io" -DMSB_BROKER_PORT="5672" -DMSB_BROKER_USER_NAME="tcuser" -DMSB_BROKER_PASSWORD="T00easy!" -DMSB_BROKER_VIRTUAL_HOST="/tcuser"
  artifact_folder: .
  group: com.thomascook.ids.sapbw
  artifact: sapbw-enrich-booking
  packaging: jar
notifications:
  build_fail: yuriy.savchuk@thomascookonline.com, igor.moroz@thomascookonline.com
  deploy:
    qa: yuriy.savchuk@thomascookonline.com
    staging: yuriy.savchuk@thomascookonline.com, igor.moroz@thomascookonline.com, pavel.agameriants@thomascookonline.com, frank.vreys@thomascookonline.com
    production: yuriy.savchuk@thomascookonline.com, igor.moroz@thomascookonline.com, pavel.agameriants@thomascookonline.com, frank.vreys@thomascookonline.com, ReleaseOneDigital@ThomasCook.com
sonar:
  pr_dryrun_enable_sonar: true
  pr_dryrun_sonar_project_suffix: PR
